name: Terraform Plan

on:
  push:
    branches:
      - feature/**
      - feat/**
      - fix/**
      - chore/**
    paths:
      - 'innovatemart-project-bedrock/terraform/**'
      - '.github/workflows/terraform-plan.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'innovatemart-project-bedrock/terraform/**'
      - '.github/workflows/terraform-plan.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

concurrency:
  group: terraform-plan
  cancel-in-progress: false

jobs:
  detect:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      tf: ${{ steps.changes.outputs.tf }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Paths filter
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            tf:
              - 'innovatemart-project-bedrock/terraform/**'
              - '.github/workflows/terraform-plan.yml'

  plan:
    name: Terraform plan (sandbox and operators)
    runs-on: ubuntu-latest
    needs: detect
    if: needs.detect.outputs.tf == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::966775992641:role/GitHubActionsInnovateMart
          aws-region: eu-west-1
          role-session-name: GitHubActions

      - name: Who am I (AWS)
        run: |
          aws sts get-caller-identity
          echo "AWS_REGION=${AWS_REGION}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Init (sandbox)
        working-directory: innovatemart-project-bedrock/terraform/envs/sandbox
        run: terraform init -input=false

      - name: Terraform Plan (sandbox)
        working-directory: innovatemart-project-bedrock/terraform/envs/sandbox
        run: terraform plan -input=false -out=tfplan

      - name: Upload Plan (sandbox)
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-sandbox
          path: innovatemart-project-bedrock/terraform/envs/sandbox/tfplan

      - name: Terraform Init (operators)
        working-directory: innovatemart-project-bedrock/terraform/envs/operators
        run: terraform init -input=false

      - name: Terraform Plan (operators)
        working-directory: innovatemart-project-bedrock/terraform/envs/operators
        run: terraform plan -input=false -out=tfplan

      - name: Upload Plan (operators)
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-operators
          path: innovatemart-project-bedrock/terraform/envs/operators/tfplan